### ISSUE TITLE
Implement JSON configuration rather than env vars

### ISSUE THREAD

**Issue by AshKyd** [abcnews/chatfuel-feed-reader#1]
Using `docker-compose.yaml` it's not possible to configure vars with emoji values. For the moment I've hard-coded the var in question, but we should improve JSON configuration with a config file.

**Comment by drzax** [comment]
Is it possible to use an external env file so the emoji doesn't need to go in the yaml? 

https://docs.docker.com/compose/env-file/
https://docs.docker.com/compose/compose-file/#env_file

**Comment by AshKyd** [comment]
I did have a look at that but was a bit vague and I didn't want to spend too much time on trial & error. I've resolved this with the attached config file in #2. Planning to merge it now. :+1:
